[package]
name = "mf1"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Use ICU Messageformat 1 to internationalise your apps"

[dependencies]

mf1-macros = { path = "../mf1-macros", optional = true}

[features]

default = ["macros"]
macros = ["mf1-macros"]
