[package]
name = "kitchen-sink"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
expect-test = "1.5.0"

mf1 = { version = "0.1.7", path = "../../crates/mf1" }

[package.metadata.mf1]
locales = ["en", "es"]
